# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36b0de8459ac8ceaa27c06d4f30a5dbee63ab728ebe2ce42b13d5821b05042de10180efa5659690fe9551357a7cf1466eddae612ad7b4dca3d24b1c2cadf8feb

test:
  secret_key_base: 8000ed5e9e93ec3f702678f3246b01319e99510a184c310f478d49f0cefee0267667044c898587971f1436fac877e51c1dc91376976016dd7a30fd662601a44a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
